ARG NODE_VERSION=20.9.0
ARG ALPINE_VERSION=3.19.1

FROM node:${NODE_VERSION}-alpine AS node

FROM alpine:${ALPINE_VERSION}

COPY --from=node /usr/lib /usr/lib
COPY --from=node /usr/local/lib /usr/local/lib
COPY --from=node /usr/local/include /usr/local/include
COPY --from=node /usr/local/bin /usr/local/bin

RUN apk add go
RUN export PATH=$PATH:/usr/local/go/bin
RUN export GOBIN=/usr/local/go/bin
RUN go install github.com/nats-io/natscli/nats@latest
# RUN /usr/local/go/bin/nats context add nats --server nats:4222 --description "NATS Prod" --select

RUN apk update
RUN apk add --upgrade powershell   
RUN apk add go

WORKDIR /koksmat
COPY . .
WORKDIR /koksmat/.koksmat/app
RUN go install

WORKDIR /koksmat/.koksmat/web

RUN npm install -g pnpm
RUN pnpm install
RUN pnpm build

EXPOSE 4323

CMD [ "pnpm","start"]