// -------------------------------------------------------------------
// Generated by 365admin-publish 
// Service wrapper  v1
// -------------------------------------------------------------------
/*
---
title: Submit Orders
---
*/
package cmds
import (
"context"
"encoding/json"
"os"
"path"
"github.com/nats-io/nats.go"
"github.com/nats-io/nats.go/micro"
"github.com/spf13/cobra"
"github.com/365admin/nexi-cava/schemas"
"github.com/365admin/nexi-cava/execution"
"github.com/365admin/nexi-cava/utils"
)
func MagicSubmitOrdersPost(ctx context.Context, args  []string)  ( *string, error) {

_, pwsherr := execution.ExecutePowerShell("john","*","nexi-cava","00-magic","10-close-delivery.ps1","" )
if (pwsherr != nil) {
	return nil,pwsherr
}
return nil, nil
	
// end result mapping

func init(){
	
}
}
