// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Room Order Changes
---
*/
package cmds

import (
	"context"

	"github.com/365admin/nexi-cava/execution"
)

func EventsRoomOrderPost(ctx context.Context, args []string) (*string, error) {

	_, pwsherr := execution.ExecutePowerShell("john", "*", "nexi-cava", "30-events", "10-room-order.ps1", "")
	if pwsherr != nil {
		return nil, pwsherr
	}
	return nil, nil

}
