// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Submit Orders
---
*/
package cmds

import (
	"context"

	"github.com/365admin/nexi-cava/execution"
)

func MagicSubmitOrdersPost(ctx context.Context, args []string) (*string, error) {

	_, pwsherr := execution.ExecutePowerShell("john", "*", "nexi-cava", "00-magic", "00-submit-orders.ps1", "")
	if pwsherr != nil {
		return nil, pwsherr
	}
	return nil, nil

}
