// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Close Delivery
---
*/
package cmds

import (
	"context"

	"github.com/365admin/nexi-cava/execution"
)

func MagicCloseDeliveryPost(ctx context.Context, args []string) (*string, error) {

	_, pwsherr := execution.ExecutePowerShell("john", "*", "nexi-cava", "00-magic", "10-close-delivery.ps1", "")
	if pwsherr != nil {
		return nil, pwsherr
	}
	return nil, nil

}
