// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Web deploy to production
---
*/
package cmds

import (
	"context"

	"github.com/365admin/nexi-cava/execution"
)

func ProvisionWebdeployproductionPost(ctx context.Context, args []string) (*string, error) {

	_, pwsherr := execution.ExecutePowerShell("john", "*", "nexi-cava", "60-provision", "20-web.ps1", "")
	if pwsherr != nil {
		return nil, pwsherr
	}
	return nil, nil

}
