// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Generate Sample Data
---
*/
package cmds
import (
"context"
"encoding/json"
"os"
"path"
"github.com/spf13/cobra"
"github.com/365admin/nexi-cava/schemas"
"github.com/365admin/nexi-cava/execution"
"github.com/365admin/nexi-cava/utils"
)
func TasksGenerateSampleDataPost(ctx context.Context, args  []string)  ( *string, error) {
	
	_, pwsherr := execution.ExecutePowerShell("john","*","nexi-cava","20-tasks","00-generate-sample-data.ps1","" )
	if (pwsherr != nil) {
		return nil,pwsherr
	}
	return nil, nil
	


}
