// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Update Rooms
---
*/
package cmds

import (
	"context"

	"github.com/365admin/nexi-cava/execution"
)

func TasksUpdateroomsPost(ctx context.Context, args []string) (*string, error) {

	_, pwsherr := execution.ExecutePowerShell("john", "*", "nexi-cava", "20-tasks", "10-step1.ps1", "")
	if pwsherr != nil {
		return nil, pwsherr
	}
	return nil, nil

}
