// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------

package endpoints

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/swaggest/rest/nethttp"
	"github.com/swaggest/rest/web"
)

func AddEndpoints(s *web.Service, jwtAuth func(http.Handler) http.Handler) {
	s.Route("/v1", func(r chi.Router) {
		r.Group(func(r chi.Router) {
			//r.Use(adminAuth, nethttp.HTTPBasicSecurityMiddleware(s.OpenAPICollector, "User", "User access"))
			r.Use(jwtAuth, nethttp.HTTPBearerSecurityMiddleware(s.OpenAPICollector, "Bearer", "", ""))
			//	r.Use(rateLimitByAppId(50))
			//r.Method(http.MethodPost, "/", nethttp.NewHandler(ExchangeCreateRoomsPost()))
			r.Method(http.MethodPost, "/magic/submit-orders", nethttp.NewHandler(MagicSubmitOrdersPost()))
r.Method(http.MethodPost, "/magic/submit-orders", nethttp.NewHandler(MagicSubmitOrdersPost()))
r.Method(http.MethodPost, "/magic/invoice", nethttp.NewHandler(MagicInvoicePost()))
r.Method(http.MethodPost, "/tasks/generate-sample-data", nethttp.NewHandler(TasksGenerateSampleDataPost()))
r.Method(http.MethodPost, "/tasks/invoice", nethttp.NewHandler(TasksInvoicePost()))
r.Method(http.MethodPost, "/tasks/invoice", nethttp.NewHandler(TasksInvoicePost()))
r.Method(http.MethodPost, "/provision/webdeployproduction", nethttp.NewHandler(ProvisionWebdeployproductionPost()))

		})
	})

}

