// -------------------------------------------------------------------
// Generated by 365admin-publish/api/20 makeschema.ps1
// -------------------------------------------------------------------
/*
---
title: Room Order Changes
---
*/
package endpoints

import (
	"context"

	"github.com/365admin/nexi-cava/execution"
	"github.com/swaggest/usecase"
)

func EventsRoomOrderPost() usecase.Interactor {
	type Request struct {
	}
	u := usecase.NewInteractor(func(ctx context.Context, input Request, output *string) error {

		_, err := execution.ExecutePowerShell("john", "*", "nexi-cava", "30-events", "10-room-order.ps1", "")
		if err != nil {
			return err
		}

		return err

	})
	u.SetTitle("Room Order Changes")
	// u.SetExpectedErrors(status.InvalidArgument)
	u.SetTags("Events")
	return u
}
