// -------------------------------------------------------------------
// Generated by 365admin-publish/api/20 makeschema.ps1
// -------------------------------------------------------------------
/*
---
title: Close Delivery
---
*/
package endpoints

import (
	"context"

	"github.com/365admin/nexi-cava/execution"
	"github.com/swaggest/usecase"
)

func MagicCloseDeliveryPost() usecase.Interactor {
	type Request struct {
	}
	u := usecase.NewInteractor(func(ctx context.Context, input Request, output *string) error {

		_, err := execution.ExecutePowerShell("john", "*", "nexi-cava", "00-magic", "10-close-delivery.ps1", "")
		if err != nil {
			return err
		}

		return err

	})
	u.SetTitle("Close Delivery")
	// u.SetExpectedErrors(status.InvalidArgument)
	u.SetTags("Magic Buttons")
	return u
}
